# Generated by Django 5.2.12 on 2026-04-04 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='last_registration',
            new_name='last_date',
        ),
        migrations.AddField(
            model_name='policy',
            name='annual_income_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='documents',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('gen', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('agiriculture', 'Agriculture'), ('education', 'Education'), ('health', 'Health'), ('employment', 'Employment'), ('housing', 'Housing'), ('social welfare', 'Social Welfare'), ('technology', 'Technology'), ('environment', 'Environment'), ('transportation', 'Transportation'), ('energy', 'Energy'), ('finance', 'Finance'), ('other', 'Other')], max_length=20),
        ),
    ]
