# Generated by Django 5.2.12 on 2026-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_last_registration_policy_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('education', 'Education'), ('health', 'Health'), ('employment', 'Employment'), ('housing', 'Housing'), ('social welfare', 'Social Welfare'), ('technology', 'Technology'), ('environment', 'Environment'), ('transportation', 'Transportation'), ('energy', 'Energy'), ('finance', 'Finance'), ('other', 'Other')], max_length=20),
        ),
    ]
